### ISSUE TITLE
一部仕様変更について

### ISSUE THREAD

**Issue by d-yano** [odentools/diagram#10]
以下の点について仕様変更？をしたいと思っています。

APIディレクトリの名前変更
Yoshidaディレクトリの名前変更
.php形式のAPI破棄→.jsonへ
sjn.php→ signage.php

後、出来る限りファイル名の大文字を無くしたいです。

よろしいでしょうか？
ご意見など、お願いします。

**Comment by mugifly** [comment]
WebAPIの仕様についてですが、
http://d.hatena.ne.jp/cou929_la/20130121/1358776754
のeBookを読んだことはありますか？私は結構好きです。

**Comment by d-yano** [comment]
始めて見ました。

URLでのバージョン分けなどすぐに出来るところからやっていきたいです！
