### ISSUE TITLE
デプロイの自動化

### ISSUE THREAD

**Issue by mugifly** [odentools/diagram#20]
masterブランチをproductionへ自動デプロイするようにしてはいかがでしょうか。

方法としては例えば...
- Herokuのようなホスティングサービスを使う。[vm-signage](https://github.com/odentools/vm-signage)でもやってるけど、独自ドメインも使えますし、お手軽です。
- 自前サーバに https://gist.github.com/mugifly/5087897 のようなスクリプトを置いて自動デプロイをかける。

**Comment by d-yano** [comment]
デプ自動化しました。

yoshidaBuranti to prototype
masterBuranti to default
