### ISSUE TITLE
Editor - 時刻表のソート

### ISSUE THREAD

**Issue by mugifly** [odentools/diagram#25]
ダイアグラムエディタの時刻表を自動ソートする

**Comment by d-yano** [comment]
自動ソートだと挿入されている事がわかりにくくなるので手動ソートでいいでしょうか？

もしくは、最新の項目をハイライトさせるかとかでしょうか？

#26　と合わせて対応します。

**Comment by mugifly** [comment]
> もしくは、最新の項目をハイライトさせるかとかでしょうか？

僕はそれも良いかなと思いました。
宜しくお願いします m(_ _)m

**Comment by d-yano** [comment]
上記で対応済み
