### ISSUE TITLE
画面UIの拡張

### ISSUE THREAD

**Issue by d-yano** [odentools/diagram#3]
下記ページ内のCanvasをドロップ操作しても、左右にオフセットが移動しない。
また、オフセットと言う文言が分かりにくいので修正をお願いします。

http://oecu.pw/Yoshida/diagram.html

**Comment by ht12a101** [comment]
文言修正を依頼する場合，文言修正案を考えてください．

**Comment by d-yano** [comment]
修正前：オフセット
修正後候補：画面位置、表示位置、表示時刻などはどうでしょうか？

また。Canvas全体の中でどの範囲が表示されているかがわかるビューがあると分かりやすいと思います。

**Comment by d-yano** [comment]
Canvasのドラッグ操作吉田くん対応済みでした。

文言修正と上記のビュー機能は一度保留で。
