### ISSUE TITLE
APIの不足

### ISSUE THREAD

**Issue by ht12a101** [odentools/diagram#4]
DiaGroupT（ダイアグループ）テーブルでRoutListT_ID_（路線リストテーブルID_）を条件に絞り込みを行い，DiaName(ダイア名)のリストを返すAPIが必要

http://oecu.pw/API/DiaGroup.php

**Comment by d-yano** [comment]
上記内容について修正を行いました。
下記のアドレスにて確認下さい。
また、RoutListT_ID_ではなく、RouteListT_ID_でないでしょうか？

http://oecu.pw/API/DiaGroup.php?RouteListT_ID_=2

**Comment by ht12a101** [comment]
対応の確認できました．
カラム名についてはこちらのミスでした．
