### ISSUE TITLE
APIのダイア複数検索対応

### ISSUE THREAD

**Issue by d-yano** [odentools/diagram#51]

**Comment by mugifly** [comment]
これは #53 に関連するものでしょうか。

**Comment by d-yano** [comment]
はい，そうです．

**Comment by ht12a092** [comment]
履歴を利用したいので、ダイアグループの重複登録にいて #53 で議論したいと思います。

**Comment by d-yano** [comment]
この題目についてですが。
SQLの修正を行えばどちらにも対応できるので。

汎用性をもたせた形にSQL修正を行って一度閉じたいのですが、どうでしょうか？

**Comment by d-yano** [comment]
とりあえず上記の件について、
Change: APIのダイア複数検索対応 #58 で対応しました。

確認お願いします。

プルリクエスト出しているので、一度閉じます。
