### ISSUE TITLE
ダイアの重複登録にいて

### ISSUE THREAD

**Issue by d-yano** [odentools/diagram#53]
> @odentools/timetable ダイアグループの重複登録が可能ですが、増便ダイアなどで複数のダイアグループを1日に割り当てる事が可能でもいいと思います。
> どうでしょうか?

@ht12a092 例えば特定の1日において、通常ダイアと特別ダイアを結合して取り出せる感じでしょうか？
それでも良いかもしれませんが、単純に通常ダイアをコピーして特別ダイアを書くような簡素な設計でも良いとは思います。もしよければ、別途議論しませんか？

**Comment by mugifly** [comment]
コピーで対応するほうが仕様上簡素であり、利用上もきっと容易に扱える？
結合するほうが、利用上の利便性は高い？

結合するとすると、例えば何かのイベントのとき、通常ダイアのうち1便だけは存在しないという場合はどうやって対応しますか？

**Comment by d-yano** [comment]
> コピーで対応するほうが仕様上簡素であり、利用上もきっと容易に扱える？

ダイア編集画面から類似のダイアをコピーすることで対応したいと思います。
ダイアのコピー機能 #36

> 結合するほうが、利用上の利便性は高い？

こちらは、カレンダでの機能として保持しておく

このような対応でどうでしょうか？

**Comment by mugifly** [comment]
了解です。

> こちらは、カレンダでの機能として保持しておく

これはどんな感じですか？
カレンダ上で複数のダイアを表示できるようにしておくということですか？

**Comment by d-yano** [comment]
> カレンダ上で複数のダイアを表示できるようにしておくということですか？

そういう意味です。

**Comment by mugifly** [comment]
なるほど。了解しました。

**Comment by d-yano** [comment]
ダイアのコピー機能 #36
APIのダイア複数検索対応 #51

上記の2点修正で解決するので、閉じます。
