### ISSUE TITLE
WebAPIおよびデータベースの名称変更

### ISSUE THREAD

**Issue by mugifly** [odentools/diagram#54]
WebAPIのパラメータおよびデータベーステーブルなどの適切な名称への変更。
#### 路線に属する「時刻表」(例: 平日, 休日, 平日学休期, 休日学休期, オープンキャンパス, etc...)

ダイアグループ(DiaGroup) → ダイア(Dia) 
#### 時刻表に属する「便」(例: 10:00の○○経由便, 11:00の直通便)

ダイア(Dia) → 便(Bus)

**Comment by mugifly** [comment]
現状のWebAPIはRouteList, DiaGroup, Diaの3つがありますが、今後は公開WebAPIとしては次の2つがあれば良いという事になりますね。
- 路線API - RouteList
- 時刻表API - Dia

(実際には日本のダイヤグラムにあたるものは、時刻表/Timetableが適切らしいけど、まあいいでしょう。)

**Comment by d-yano** [comment]
DB修正図を作りました。

確認よろしくお願いします。

![snapcrab_noname_2015-5-27_12-3-16_no-00](https://cloud.githubusercontent.com/assets/11460169/7827981/6e805c0c-0468-11e5-808a-0a2ae1540370.png)

**Comment by mugifly** [comment]
今思ったのですが、他のテーブル名称を見たところ、RouteListTはRouteTでもいいかもしれませんね。

もうひとつ。現在...
- RouteName = "スクールバス ○○キャンパス行"
- Management = "大阪電気通信大学"

のようになっているかと思うのですが、RouteNameの文字列がアプリケーションで表示するには長過ぎる為、
以下のようにプレフィックスと分けるという話があったかと思いますが、データベース側で分けておきませんか？

例: RoutePrefix = "スクールバス"、RouteName = "○○キャンパス行"

**Comment by d-yano** [comment]
> RouteListTはRouteTでもいいかもしれませんね。

そうですね、できるだけ短くしたいですね。
ありがとうございます、統一させます。

> 例: RoutePrefix = "スクールバス"、RouteName = "○○キャンパス行"

いま更なのですが、Management +RouteName = "○○キャンパス行"で事足りるような気もしてきました。
でも、使い方次第なので追加します。

それと、RouteTに以下の4つを追加したいと思います。
API/RouteList - 緯度経度情報の追加 #5 も合わせて検討したです。

**Comment by mugifly** [comment]
ありがとうございます。

> いま更なのですが、Management +RouteName = "○○キャンパス行"で事足りるような気もしてきました。
> でも、使い方次第なので追加します。

たしかにそうかもしれませんね。

> それと、RouteTに以下の4つを追加したいと思います。

4つというと...
- RoutePrefix
- DepartureLocation
- ArrivalLocation

とあと一つなんでしたっけ。
それともLocationを2つずつ(lat, lng)ということですか？

**Comment by d-yano** [comment]
RoutePrefix とは別に位置情報を4つ追加したいと思います。

> それともLocationを2つずつ(lat, lng)ということですか？
> Locationには、4つカラムを利用したいと考えています。

**Comment by mugifly** [comment]
そうですね。検索も考えた上で...doubleで十分でしょうか。
MySQLならGeometryという手もありますね。

**Comment by d-yano** [comment]
> そうですね。検索も考えた上で...doubleで十分でしょうか。

doubleで作成しました。

![snapcrab_noname_2015-5-27_12-51-59_no-00](https://cloud.githubusercontent.com/assets/11460169/7828513/6836dbc6-046f-11e5-882b-fad75d44b3ab.png)

**Comment by mugifly** [comment]
DB図を確認しました。
LatとLngをそれぞれ追加したうえでDepartureLocationとArrivalLocationも残すということですか？

**Comment by d-yano** [comment]
はい。

> LatとLngをそれぞれ追加したうえでDepartureLocationとArrivalLocationも残すということですか？

位置情報のみの方がいいでしょうか?

**Comment by mugifly** [comment]
それってArrival/DepartureLocationは文字列ということですか？○○駅バス停とか、○○キャンパスとか。
緯度経度だけで良いかなと思っていましたが、それもありかもしれませんね。

**Comment by d-yano** [comment]
はい、文字列です。
位置情報は、任意の追加情報にしたいと思いました。

**Comment by mugifly** [comment]
なるほど。了解です。

だとしたらArrivalLocationNameみたいにしたほうが文字列っぽいかなと思ったりするのですが、まぁそれはどちらでも(笑)

**Comment by d-yano** [comment]
それでは、このような形で行きたいと思います。

ただ、カラム名が長くなってしまいましたね。

![snapcrab_noname_2015-5-27_13-49-5_no-00](https://cloud.githubusercontent.com/assets/11460169/7829017/3b757c20-0477-11e5-96b9-a1d68cd859a4.png)

**Comment by mugifly** [comment]
ですよねー。MongoDBみたいなドキュメント指向DBだとカラム名を極力短くしないとデータ量が増加してあれですけど、RDBだと実質困ることもないですよね。

**Comment by d-yano** [comment]
DB名　betaで作成完了しました。

旧DBからのデータはコピーしました。
完全に同期がとれているわけでは無いのでお気をつけください。

**Comment by d-yano** [comment]
本番用のDB図確認下さい。
![snapcrab_noname_2015-5-29_21-13-2_no-00](https://cloud.githubusercontent.com/assets/11460169/7882344/945dd77a-0647-11e5-8620-89eaf20f627b.png)

**Comment by d-yano** [comment]
一部修正しました。
![snapcrab_noname_2015-5-29_21-20-16_no-00](https://cloud.githubusercontent.com/assets/11460169/7882435/9173a82c-0648-11e5-9d72-c3c355410d28.png)

**Comment by d-yano** [comment]
上記で対応しました。
確認お願いします。

こちらも、リクエスト出したので閉じます。
