### ISSUE TITLE
API - minパラメータのデフォルト化

### ISSUE THREAD

**Issue by mugifly** [odentools/diagram#55]
全APIについて現在のminパラメータをつけた状態をデフォルトとする。
ダイアグラムエディタのために必要な情報を要求する場合は、別途パラメータを設ける。

**Comment by d-yano** [comment]
別途必要なパラメータをdevelopをし修正を行いたいと思います。

**Comment by mugifly** [comment]
"?develop"みたいにするということですね。 了解です。

**Comment by d-yano** [comment]
対応しました。
確認お願いします。
