### ISSUE TITLE
API - プロパティ名の統一

### ISSUE THREAD

**Issue by mugifly** [odentools/diagram#62]
現行のWebAPIですが、データベースからカラム名をそのまま持ってきているからか、
idやRouteNameといったようにプロパティ名に形式の揺れが存在します。

今は適宜アプリケーション側で直したりして対応しているのですが、統一しませんか？
私としてはJavaやJavaScriptでのオブジェクトプロパティ名の慣習にあわせて、ローワーキャメルケースが良いかと思います。
[Google JSON Style Guide](http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml#Property_Name_Format)でも推奨しています。

**Comment by d-yano** [comment]
> プロパティ名に形式の揺れが存在します。

確かに統一性がなく気持ち悪いですね。

> 私としてはJavaやJavaScriptでのオブジェクトプロパティ名の慣習にあわせて、ローワーキャメルケースが良いかと思います。

そうですね、それで行きたいと思います。

**Comment by mugifly** [comment]
では、#60 はこちらの変更を終えてからマージということにしましょうか。宜しくお願いします。

**Comment by d-yano** [comment]
WebAPIおよびデータベースの名称変更 #54
こちらを再度開いたので、DBと合わせて統一します。

DB側で対応したいと思いますのでこちらは一度閉じます。
