### ISSUE TITLE
API - 適切なHTTPステータスコードによる応答

### ISSUE THREAD

**Issue by mugifly** [odentools/diagram#8]
JSON APIの応答で404などのステータスコードがボディに含まれるようになりましたが、
HTTPステータスコードが200のままなので適切に応答を返して下さい。

**Comment by d-yano** [comment]
@mugifly 以下の仕様変更でどうでしょうか?

[変更ページ](http://oecu.pw/API/RouteList.json)

**Comment by mugifly** [comment]
バッチリです :+1:
