### ISSUE TITLE
当日ダイヤがない場合にrouteAPIの動作について

### ISSUE THREAD

**Issue by d-yano** [odentools/diagram#99]
当日ダイヤがないルートはAPIで検索を行った時に専用のパラメータを付加する。

トップページでの、不要なダイア表示を抑制できるのではないでしょうか？

**Comment by mugifly** [comment]
:+1: 良いですね。それをどう扱うかはアプリケーション次第で決めればよいですし。

**Comment by d-yano** [comment]
別ブランチで、作業に入りたいと思います。
また、確認よろしくお願いします。

**Comment by mugifly** [comment]
ありがとうございます。宜しくお願いします。

**Comment by d-yano** [comment]
serviceNumberForTodayという項目を追加しました。
この項目は、当日の運行数を示しています。
apiのバージョンは1.3.1としています。
